CREATE DATABASE IF NOT EXISTS mooc;
CREATE DATABASE IF NOT EXISTS backoffice;
CREATE DATABASE IF NOT EXISTS shared;

GRANT ALL PRIVILEGES ON mooc.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON backoffice.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON shared.* TO 'user'@'%';
FLUSH PRIVILEGES;
